import Head from "next/head";
import { onSnapshot, collection, query, orderBy } from "firebase/firestore";
import { useEffect, useState } from "react";
import {
  handleEdit,
  handleNew,
  handleDelete,
  handleQueryDelete,
} from "../firebase/util";
import db from "../firebase/firebase";

export default function Home() {
  const [todos, setTodos] = useState([{ name: "Loading ...", id: "initial" }]);

  // console.log(todos);

  useEffect(() => {
    const collectionRef = collection(db, "todos");
    const q = query(collectionRef, orderBy("timestamp", "desc"));

    const unsub = onSnapshot(q, (snapshot) =>
      setTodos(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })))
    );
    return unsub;
  }, []);

  return (
    <div className="bg-gray-100 h-screen">
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" ">
        <div className="flex flex-col max-w-xl mx-auto space-y-2">
          <div className="flex items-center justify-center  font-bold text-2xl">
            <h1>Todo app</h1>
          </div>

          <div className="flex justify-between">
            <div>
              <button
                onClick={handleNew}
                className="bg-yellow-100 p-2 rounded-lg shadow-lg  font-bold hover:bg-yellow-300"
              >
                Add new Todo
              </button>
            </div>
            <div>
              <button
                onClick={handleQueryDelete}
                className="bg-orange-400 p-2 rounded-lg shadow-lg  font-bold hover:bg-orange-500"
              >
                Query delete
              </button>
            </div>
          </div>
          {todos.map((todo) => (
            <div
              key={todo.id}
              className="border border-gray-400 rounded-md p-2 shadow-xl shadow-gray-300"
            >
              <div>
                <div className="space-y-2">
                  <div className="bg-gray-200 rounded-md">
                    <h1 className="p-1 align-middle  items-center font-bold w-full  ml-2 ">
                      {" "}
                      {todo.title}
                    </h1>
                  </div>{" "}
                  {/*  */}
                  <div className="bg-gray-300 rounded-md">
                    <h1 className="h-14 font-bold m-3">{todo.description}</h1>
                  </div>
                  {/*  */}
                  <div className="flex justify-between items-center">
                    <div>
                      <button
                        onClick={() => handleEdit(todo.id)}
                        className="bg-blue-300 py-1 px-4 rounded-lg hover:bg-blue-500 font-bold text-md"
                      >
                        Edit
                      </button>
                    </div>
                    {/*  */}
                    <div>
                      {" "}
                      <button
                        onClick={() => handleDelete(todo.id)}
                        className="bg-red-300 py-1 px-2 rounded-lg hover:bg-red-500 font-bold text-md"
                      >
                        Delete
                      </button>
                    </div>
                  </div>
                  {/*  */}
                </div>
              </div>
            </div>
          ))}
        </div>
        {/* <Card /> */}
      </main>
    </div>
  );
}
